@server = http://127.0.0.1:8082

### TABLE LIST
GET {{server}}
### UNKNOWN TABLE
GET {{server}}/unknown
### ITEMS LIST
GET {{server}}/items
    ?offset=0
    &limit=3
### ITEM INFO
GET {{server}}/items/3
### ITEM NOT FOUND
GET {{server}}/items/100500
### DELETE ITEM
DELETE {{server}}/items/3
### INSERT ITEM
PUT {{server}}/items
Content-Type: application/json

{
    "id": 42,
    "title": "db_crud", 
    "description": ""
}
### UPDATE ITEM
POST {{server}}/items/9
Content-Type: application/json

{
    "updated": null,
    "description": "Написать программу db_crud"
}